spring:
  datasource:
    url: jdbc:h2:mem:teammanagerdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
  servlet:
    context-path: /api
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  paths-to-match: /api/**

security:
  basic:
    enabled: true

google:
  calendar:
    application-name: TeamManager
    tokens-directory-path: tokens 